version: "3"
services:
  backend:
    build:
      context: ./Backend/
    volumes:
      - /app/node_modules
      - ./Backend:/app
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3001:8080"
    volumes:
      - /app/node_modules
      - ./Frontend:/app
